# Generated by Django 5.2.5 on 2026-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_salesproductcolor_salesproductvariant_salesinventory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="street",
            new_name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="address",
            name="province",
        ),
        migrations.AddField(
            model_name="address",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
