# Generated by Django 5.2.5 on 2026-09-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_rename_street_address_delivery_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="city",
            new_name="delivery_city",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
