# Generated by Django 5.2.5 on 2026-09-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_rename_city_order_delivery_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="product_name",
            field=models.CharField(
                default="",
                help_text="Product name at the time of purchase",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
