# Generated by Django 5.2.5 on 2026-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_orderdetail_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True, help_text="Snapshot of address at time of order", null=True
            ),
        ),
    ]
