# Generated by Django 5.2.5 on 2026-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="images",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
